name: Prepare Release
on:
  workflow_dispatch:
   
jobs:
  prepare:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Configure Git User
        run: |
          git config user.email "thiagolvlsantos@gmail.com"
          git config user.name "Thiago Santos"
      - name: Configure SSH
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          echo ${{ secrets.GIT_PUBLIC_KEY }} > ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
      - name: Publish package
        run: mvn -X -U -B -Prelease release:clean release:prepare
        env:
          GITHUB_ACTOR: thiagolvlsantos
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} # has to be other, the original which has not commit rigths
