name: Prepare Release
on:
  workflow_dispatch:
   
jobs:
  prepare:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Git User
        run: |
          git config --global user.email "thiagolvlsantos@gmail.com"
          git config --global user.name "Thiago Santos"
      - name: Publish package
        run: mvn -U -B -Prelease release:clean release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
