name: Release
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person`s name'
        required: true
      home:
        description: 'Location name.'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
